language: python
python:
  - '2.7'
# command to install dependencies
install:
  - 'easy_install -U setuptools'
  - 'pip install -U pip'
  - 'pip install wheel'
  - 'pip install -e .[tests]'
# command to run tests
script:
  - 'py.test -svvv --cov-report term-missing --cov bugbuzz tests'
  - 'pip install flake8'
  - 'flake8 bugbuzz --ignore=E501,W293'
